package utils;

import java.awt.Color;
import java.awt.Font;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;

import mainPackage.Main;
import servicesHandler.LoginHandler;
import utils.Session;
import org.jdesktop.application.*;
public class Login extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Login.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jPasswordField1.setText(resourceMap.getString("passwordF.text")); // NOI18N
        jPasswordField1.setName("passwordF"); // NOI18N

        jTextField1.setText(resourceMap.getString("usernameF.text")); // NOI18N
        jTextField1.setName("usernameF"); // NOI18N

        fatalErrorTitle = resourceMap.getString("fatalErrorTitle.text");
        falalErrorMsg = resourceMap.getString("fatalErrorMsg.text");
        lengthErrorUsername = resourceMap.getString("lengthErrorUsername.text");
        formatErrorUsername = resourceMap.getString("formatErrorUsername.text");
        lengthErrorPassword = resourceMap.getString("lengthErrorPassword.text");
        formatErrorPassword = resourceMap.getString("formatErrorPassword.text");
        errorMsg = resourceMap.getString("errorMsg.text");
        
        jButton1.setText(resourceMap.getString("okButton.text")); // NOI18N
        jButton1.setName("okButton"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setLabel(resourceMap.getString("cancelButton.label")); // NOI18N
        jButton2.setName("cancelButton"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("loginHint.text")); // NOI18N
        jLabel1.setName("loginHint"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)
                                .addGap(52, 52, 52)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordField1)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(24, 24, 24)))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	String text = jPasswordField1.getText();
		LoginHandler login = new LoginHandler(jTextField1.getText(),text);
    	Font font = new Font("Serif", Font.BOLD, 10);
    	resetHints();
    	boolean valid = validFields(jTextField1.getText(),text);
    	if(!valid){
    		return;
    	}
    	if(login.datos==null){
    		JOptionPane.showMessageDialog(null,fatalErrorTitle,falalErrorMsg,JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	else if(login.datos.get(0).equals("-1")){
    		jLabel1.setText(errorMsg);
    		jLabel1.setFont(font);
    		jLabel1.setForeground(Color.RED);
    		return;
    	}
    	Session session = Session.getSession();
    	session.token=login.datos.get(0);
    	session.id=login.datos.get(1);
    	session.username=login.datos.get(2);
    	session.name=login.datos.get(3);
    	session.last_login=login.datos.get(4);
    	Main.toggleLoginOn();
    	dispose();
    }

    private boolean validFields(String username ,String password){
    	Font font = new Font("Serif", Font.BOLD, 10);
    	String aux;
    	if(username.length()<Constants.usernameLengthMin || username.length()>Constants.usernameLengthMax){
    		jLabel1.setText(lengthErrorUsername);
    		jLabel1.setFont(font);
    		jLabel1.setForeground(Color.RED);
    		return false;
    	}
    	if(!username.matches(Constants.usernameRegExp)){
    		jLabel1.setText(formatErrorUsername);
    		jLabel1.setFont(font);
    		jLabel1.setForeground(Color.RED);
    		return false;
    	}
    	
    	
    	if(password.length()<Constants.passwordLengthMin || password.length()>Constants.passwordLengthMax){
    		jLabel1.setText(lengthErrorPassword);
    		jLabel1.setFont(font);
    		jLabel1.setForeground(Color.RED);
    		return false;
    	}
    	if(!password.matches(Constants.passwordRegExp)){
    		jLabel1.setText(formatErrorPassword);
    		jLabel1.setFont(font);
    		jLabel1.setForeground(Color.RED);
    		return false;
    	}
    	return true;
    }
    
    private void resetHints() {
    	jLabel1.setText(" ");

    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private String errorMsg;
    private String lengthErrorUsername;
    private String formatErrorUsername;
    private String lengthErrorPassword;
    private String formatErrorPassword;
    private String fatalErrorTitle;
    private String falalErrorMsg;
    // End of variables declaration
}

